GET http://localhost:3000 HTTP/1.1

###

POST http://localhost:3000/createOrder
content-type: application/json

{
    "key":"o1",
    "sellerId":"s1",
    "buyerId":"b1",
    "orderDeliveryDate":"7/10/2121" 
}

###

POST http://localhost:3000/depositBuyer
content-type: application/json

{
    "key":"b1_o1_tx1",
    "buyerId":"b1",
    "sellerId":"s1",
    "orderId":"o1",
    "depositTransactionId":"tx1",
    "depositPaymentAmount":50
}